### ISSUE TITLE
Feature Request: Collapsible requirement sections in Project view

### ISSUE THREAD

**Issue by znb** [Santandersecurityresearch/asvs#11]
It would be super awesome to have the requirements in the project view be collapsible based on criteria.

1. Collapse all categories on page load (helps developers find a category they're interested in)
2. Collapse a category that has met all of the requirements

Kinda related, but it would also be useful to colour code the requirements based on status (red for unmet or green for completed)

**Comment by danielcuthbert** [comment]
@Birajpjpt just added a sweet PR that does this
