### ISSUE TITLE
Collapsable categories for requirements in levels 

### ISSUE THREAD

**Issue by Birajpjpt** [Santandersecurityresearch/asvs#13]
Manage the requirements in the levels in a way that it can be categorised in the categories. This will help developers easily find the requirements in their category.

**Comment by danielcuthbert** [comment]
I like this idea, thank you. Will push to see if anyone can help, or ill try myself

**Comment by Birajpjpt** [comment]
Created pull request for this issue  #14

**Comment by danielcuthbert** [comment]
@Birajpjpt you just made me very happy! thank you for this.
