### ISSUE TITLE
Template Syntax Deprecated - Django 2.1/3

### ISSUE THREAD

**Issue by thomaswoj** [Santandersecurityresearch/asvs#15]
I was unable to build the ASVS with a latest Docker install on Mac OS X. 

Changing `{% load staticfiles %}` to `{% load static %}` in the following files and rebuilding seemed to fix the issue for me. 

```
tomwoj@Tom-Woj asvs-master % grep '{% load staticfiles %}' --recursive .
./templates/home/home.html:{% extends "base.html" %} {% load staticfiles %} {% block content %}
./templates/base.html:{% load staticfiles %}
./templates/projects/view.html:{% extends "base.html" %} {% load staticfiles %} {% block content %}
./templates/levels/levels.html:{% extends "base.html" %} {% load staticfiles %} {% block content %}
./templates/help/help.html:{% extends "base.html" %} {% load staticfiles %} {% block content %}
```

Ref: https://stackoverflow.com/questions/55929472/django-templatesyntaxerror-staticfiles-is-not-a-registered-tag-library

Cheers,
Tom

**Comment by danielcuthbert** [comment]
Thanks for debugging this Tom, will change and push out a new release.
