### ISSUE TITLE
Different views

### ISSUE THREAD

**Issue by danielcuthbert** [Santandersecurityresearch/asvs#20]
Would be good to have different views for different teams (an idea from Joseph B. LeRoy @josephbleroy)

- Security team
- Developers
- Executives
- Auditors

**Comment by rubeniglesiasg** [comment]
Stopped because there arent specifications for the difference between this different roles and how would this work

**Comment by danielcuthbert** [comment]
Closing this, for now, we need to work out the best way forward as to how we might do multiple views
