### ISSUE TITLE
DIV links on project percentages

### ISSUE THREAD

**Issue by NoobieDog** [Santandersecurityresearch/asvs#35]
Please add links to the project percentages to follow down to the relevant div

![Screenshot (162)](https://user-images.githubusercontent.com/6222279/117798001-8e511500-b248-11eb-9b34-0a116203268d.png)

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/9b21d4ffdce7926da6a044e5b29dbb7771696601
