### ISSUE TITLE
DIV width change on Levels page

### ISSUE THREAD

**Issue by NoobieDog** [Santandersecurityresearch/asvs#36]
On the levels page as default, the width of the table div is half of what it is when clicked.

![Screenshot (163)](https://user-images.githubusercontent.com/6222279/117799289-dae92000-b249-11eb-90e1-febf07bfb097.png)

When clicked it expands out to full width

![Screenshot (164)](https://user-images.githubusercontent.com/6222279/117799342-e89ea580-b249-11eb-85c5-94e97bb7bfe3.png)

It would be better if the width didnt change

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/1d92713331ff0e3a11c468b2705283dec781588e
