### ISSUE TITLE
/help/6

### ISSUE THREAD

**Issue by NoobieDog** [Santandersecurityresearch/asvs#37]
Help menu 6 (crypto) causes an stack trace error, no other help page does!

![Screenshot (167)](https://user-images.githubusercontent.com/6222279/117805095-7a111600-b250-11eb-90c4-ad269e5b2324.png)

**Comment by rubeniglesiasg** [comment]
category.json has different values than the values on base.html for the help dropdown menu. Waiting for expected solution

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/a5e17a53213819ed82c4eca996ebac6554c31ded
