### ISSUE TITLE
redirect after sucessful OTP auth

### ISSUE THREAD

**Issue by NoobieDog** [Santandersecurityresearch/asvs#38]
this page should redirect to the projects page after sucessfully authenticationg OTP

![Screenshot (168)](https://user-images.githubusercontent.com/6222279/117805548-01f72000-b251-11eb-8881-b3fcb6a9544d.png)

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/d3ac3e7174408b5e4a24861cfe18a8e07797ee04
