### ISSUE TITLE
Creating a user with a duplicate username creates error

### ISSUE THREAD

**Issue by NoobieDog** [Santandersecurityresearch/asvs#39]
when registering or changing the username, if the username already exists, it causes a stack trace

![Screenshot (169)](https://user-images.githubusercontent.com/6222279/117806742-a0d04c00-b252-11eb-8fb2-e85220e2b881.png)

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/3b4009036b981672b60b080c824b90596e77edd8
