### ISSUE TITLE
Changing existing user to another reveals projects

### ISSUE THREAD

**Issue by NoobieDog** [Santandersecurityresearch/asvs#41]
in this case we have two users, notadmin and administrator

notadmin has 4 projects, adminstrator has 1

![Screenshot (171)](https://user-images.githubusercontent.com/6222279/117807441-8a76c000-b253-11eb-8184-fb6f5b6a4a0f.png)

when changing this username to another (case insensitive) (if an user with the exact username exists, see other bug, however if one character is changed case, this bug works)

![Screenshot (172)](https://user-images.githubusercontent.com/6222279/117807576-b5611400-b253-11eb-9c69-9de55539e20a.png)

Once changed, the other user can see the emulated users projects

![Screenshot (173)](https://user-images.githubusercontent.com/6222279/117807793-007b2700-b254-11eb-95bc-6e0deb1fdbd4.png)

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/4b3d3ef4e3c7d499424cd010446e5d79ed4afe4c
