### ISSUE TITLE
ASVS content on levels page

### ISSUE THREAD

**Issue by NoobieDog** [Santandersecurityresearch/asvs#44]
Links in descriptions should be a link, opening in another tab.

Description": "Verify that the application does not log other sensitive data as defined under local privacy laws or relevant security policy. ([C9](https://owasp.org/www-project-proactive-controls/#div-numbering))",

These are links in the projects page, but not the levels page

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/cb4e74ebb8dc1fd986f7c9a1d13b3c00dd730780
