### ISSUE TITLE
PDF Generation game is Weak

### ISSUE THREAD

**Issue by NoobieDog** [Santandersecurityresearch/asvs#47]
PDF generation needs to be sexier, some graphs etc.. (at the mo looks like a printable version)

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/e741f5fc08704f9342b01f22bc9e9c1c35d54e80

**Comment by danielcuthbert** [comment]
Closing this one as ideally we don't want to spend huge dev efforts in creating a legacy output format when we can integrate into Jira or other ticketing apps
