### ISSUE TITLE
Outdated External Links

### ISSUE THREAD

**Issue by NoobieDog** [Santandersecurityresearch/asvs#48]
Threat Modeling Cheat Sheet link (http://localhost:8000/help/1) points to out of date resource on OWASP site

**Comment by rubeniglesiasg** [comment]
Updated some urls on category.json, some of them are okay, but as owasp.org changes the links some of our links will just redirect to useless pages, we should try to be up to date when our external links are not available anymore

https://github.com/Santandersecurityresearch/asvs/commit/09b4c6e48e6c4f47f49b3f484feef8ba23bd7356
