### ISSUE TITLE
Migration to 4.0.2

### ISSUE THREAD

**Issue by danielcuthbert** [Santandersecurityresearch/asvs#50]
With 4.0.2 now the stable branch of the standard, we need to migrate all the variable names used previously. Attached is the new JSON for 4.0.2
[asvs.json.zip](https://github.com/Santandersecurityresearch/asvs/files/6464608/asvs.json.zip)

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/31ee83137e513f17d7a44235c842063f8e8da4d9
