### ISSUE TITLE
Enhancement: Ability to "Collapse all" the expanded Categories in Project view

### ISSUE THREAD

**Issue by znb** [Santandersecurityresearch/asvs#53]
As a user it would be helpful to have the ability to collapse all the expanded categories in the main project view.

We have different teams working on various parts of a project and it can be a little daunting to load a project page and be confronted by a huge list of expanded categories. 

If we could either load it all without expanding or have the ability to quickly collapse all the categories, it would help the teams using ASVS.

![Screenshot 2021-05-25 at 11 33 32](https://user-images.githubusercontent.com/803645/119484272-c464bd80-bd4d-11eb-9c82-e4a75693a0f2.png)

**Comment by danielcuthbert** [comment]
This is a really good idea, thanks Matt!

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/e8e233fb518199f87075bfa59f0638a332f0246f Added a button to expand or collapse all categories :)
