### ISSUE TITLE
MFA Setup Bypass

### ISSUE THREAD

**Issue by cameo-myob** [Santandersecurityresearch/asvs#54]
Hey team,
First of all - love the effort you've put in here.
I've found a slight bug in the setup for MFA. When creating a new user and you reach the MFA prompt, there are no other buttons on the screen and no way to get out of setting it up. If you click `Submit Verification Code` without entering a valid code, the page refreshes and the menu appears at the top. You can then bypass setting up MFA by just clicking out of the screen (by clicking on `Projects` or similar). I've attached some screenshots to demonstrate. 
<img width="1224" alt="Screen Shot 2021-05-26 at 7 50 17 pm" src="https://user-images.githubusercontent.com/41880739/119640474-ff551700-be5b-11eb-95e8-ddf34c568973.png">
<img width="1198" alt="Screen Shot 2021-05-26 at 7 50 26 pm" src="https://user-images.githubusercontent.com/41880739/119640483-02500780-be5c-11eb-8390-84351921119f.png">

**Comment by danielcuthbert** [comment]
Hello. Thank you, this is indeed a bug, thank you for catching this. We are on it!

**Comment by danielcuthbert** [comment]
all fixed @cameo-myob with https://github.com/Santandersecurityresearch/asvs/commit/4e84f3abd03485fe755738f435cc98d07c37d962

Thanks for reporting this, appreciate it :)
