### ISSUE TITLE
Add "note" field

### ISSUE THREAD

**Issue by maramazza** [Santandersecurityresearch/asvs#55]
Hi and first of all thanks!
I think that can be a good idea to add a field "Note" to write just one row of information for each points to use for example to remember why the test is Incomplete
Bye for now
Matteo

**Comment by danielcuthbert** [comment]
Hi

That's a good idea, adding it as an enhancement, thank you

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/commit/f80dedbfdf4c27ea6d65d1034daab9833893aaef

Notes added :) 
![image](https://user-images.githubusercontent.com/73822501/120468931-0a4f0080-c3a2-11eb-8abc-8d00e462a79c.png)
