### ISSUE TITLE
Check OWASP password length

### ISSUE THREAD

**Issue by maramazza** [Santandersecurityresearch/asvs#56]
Why the first test say
"(V2.1.1) Verify that user set passwords are at least **12** characters in length"
but if i check the OWASP project i found " at least **8** characters in length"?

https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v21-password-security-requirements

**Comment by danielcuthbert** [comment]
Hi 

We are basing this off the 4.0.3 branch https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x11-V2-Authentication.md
