### ISSUE TITLE
QR code is not working

### ISSUE THREAD

**Issue by quangnb** [Santandersecurityresearch/asvs#67]
![image](https://github.com/Santandersecurityresearch/asvs/assets/8024138/0cb72ccb-c326-4502-a039-7ae47f174780)
QR is not work, can we have 2FA disable option?

**Comment by danielcuthbert** [comment]
Arse, that's not good. Fixing it

**Comment by danielcuthbert** [comment]
Hello @quangnb 

I've just pulled down the latest code and built the image and all is working ok with my setup (116.0.3 FireFox, 116.0.1938.62 Edge)

![Screenshot 2023-08-30 at 12 31 19](https://github.com/Santandersecurityresearch/asvs/assets/7882621/dd3bd191-8552-47ad-8c4c-216f34bee7f9)

Can you share with me more details about your setup please?

**Comment by quangnb** [comment]
Hi,

I have an issue when I run it with docker on ParrotOS. When I try with
Docker on Windows, it works fine.
