### ISSUE TITLE
Feature Request: Multiple user access to projects

### ISSUE THREAD

**Issue by znb** [Santandersecurityresearch/asvs#8]
We use ASVS internally for some teams. 

It would be awesome if we could "share" the project out to internal users so they can work on it. 
Currently user A creates the project, does some work and then wants input from user B.
But user B cannot see the project for some reason. 

Shout if I can help with anything here.

**Comment by rubeniglesiasg** [comment]
https://github.com/Santandersecurityresearch/asvs/pull/26
